import "./globals.css";
import Header from "@/src/components/Header/Header";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // какие нужны
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="sk" className={montserrat.variable}>
      <Header />
      <body>{children}</body>
    </html>
  );
}
